my_site/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include
from p_library import views
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='all_links.html'), name='all_links'),
    path('index/', views.index, name='main_page'),
    path('index/book_increment/', views.book_increment),
    path('index/book_decrement/', views.book_decrement),
    path('publisher/create', views.PublisherCreate.as_view(), name='publisher_create'),
    path('publishers/', views.publishers, name='publishers'),
    path('editing/', include('p_library.urls')),
    path('accounts/', include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

p_library/urls.py
from django.contrib import admin
from django.urls import path
from .views import AuthorDelete, AuthorEdit, AuthorList, AuthorCreateMany, BooksAuthorsCreateMAny, FriendUpdate, Friends, FriendDelete, FriendCreate

app_name = 'p_library'
urlpatterns = [
    path('author/create/', AuthorEdit.as_view(), name='author_create'),
    path('author/', AuthorList.as_view(), name='authors_list'),
    path('author/create_many/', AuthorCreateMany, name='author_create_many'),
    path('author_book/create_many/', BooksAuthorsCreateMAny, name='author_book_create_many'),
    path('author/delete/', AuthorDelete, name='author_delete'),
    path('friend/', Friends, name='friend_list'),
    path('friend/create/', FriendCreate.as_view(), name='friend_create'),
    path('friend/delete/', FriendDelete, name='friend_delete'),
    path('friend/edit/<int:pk>/', FriendUpdate.as_view(), name='friend_update'),
]

p_library/models.py
from django.db import models


class Author(models.Model):
    full_name = models.TextField(verbose_name='Имя')
    birth_year = models.SmallIntegerField(verbose_name='Дата рождения')
    country = models.CharField(max_length=2, verbose_name='Страна')
    def __str__(self):
        return self.full_name

class Publisher(models.Model):
    name = models.CharField(max_length=50)
    def __str__(self):
        return self.name

class Book(models.Model):
    ISBN = models.CharField(max_length=13)
    title = models.CharField(max_length=128, verbose_name='Название')
    description = models.TextField(verbose_name='Описание')
    image = models.ImageField(upload_to='book_images', blank=True, null=True)
    year_release = models.SmallIntegerField(verbose_name='Год издания')
    authors = models.ManyToManyField(Author, through='Inspiration', through_fields=('book', 'author'), verbose_name='Авторы')
    publisher = models.ForeignKey(Publisher, on_delete=models.SET_NULL, blank=True, null=True, verbose_name='Издательство')
    copy_count = models.SmallIntegerField(default=1, verbose_name='Число экземпляров')
    price = models.DecimalField(max_digits=16, decimal_places=2, default=0, verbose_name='Цена')
    @property
    def get_image_url(self):
        if self.image and hasattr(self.image, 'url'):
            return self.image.url
        else:
            return "/media/book_images/book_default.png"
    def __str__(self):
        return self.title

class Inspiration(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)

class Friend(models.Model):
    full_name = models.CharField(max_length=128, verbose_name='Имя')
    books = models.ManyToManyField(Book, through='RentedBooks', verbose_name='Книги')
    def __str__(self):
        return self.full_name

class RentedBooks(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    friend = models.ForeignKey(Friend, on_delete=models.CASCADE)

p_library/forms.py
from django import forms
from .models import Author, Book, Friend, Publisher

class AuthorForm(forms.ModelForm):
    full_name = forms.CharField(widget=forms.TextInput)
    class Meta:
        model = Author
        fields = '__all__'

class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = '__all__'

class FriendForm(forms.ModelForm):
    class Meta:
        model = Friend
        fields = '__all__'

class PublisherForm(forms.ModelForm):
    class Meta:
        model = Publisher
        fields = '__all__'

p_library/views.py
from django.shortcuts import render, redirect
from .models import Book, Author, Friend, Publisher
from django.http import HttpResponse
from django.http.response import HttpResponseRedirect
from django.template import loader
from .forms import AuthorForm, BookForm, FriendForm, PublisherForm
from django.forms import formset_factory
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required


def books_list(request):
    books = Book.objects.all()
    return HttpResponse(books)

def index(request):
    template = loader.get_template('index.html')
    books = Book.objects.all()
    biblio_data = {
        "title": "мою библиотеку",
        "books": books,
    }
    return HttpResponse(template.render(biblio_data, request))

def book_increment(request):
    if request.method == 'POST':
        book_id = request.POST['id']
        if not book_id:
            return redirect('/index/')
        else:
            book = Book.objects.filter(id=book_id).first()
            if not book:
                return redirect('/index/')
            book.copy_count += 1
            book.save()
        return redirect('/index/')
    else:
        return redirect('/index/')


def book_decrement(request):
    if request.method == 'POST':
        book_id = request.POST['id']
        if not book_id:
            return redirect('/index/')
        else:
            book = Book.objects.filter(id=book_id).first()
            if not book:
                return redirect('/index/')
            if book.copy_count < 1:
                book.copy_count = 0
            else:
                book.copy_count -= 1
            book.save()
        return redirect('/index/')
    else:
        return redirect('/index/')

def publishers(request):
    template = loader.get_template('publishers.html')
    books = Book.objects.all().prefetch_related('publisher')
    publishers = []
    for book in books:
        if book.publisher:
            publishers.append(book.publisher.name)
    # publishers = [x.publisher.name for x in books]
    publishers = sorted(set(publishers))
    biblio_data = {
        "publishers": publishers,
        "books": books,
    }
    return HttpResponse(template.render(biblio_data, request))

class AuthorEdit(CreateView):
    model = Author
    form_class = AuthorForm
    success_url = reverse_lazy('p_library:authors_list')
    template_name = 'author_edit.html'
    def dispatch(self, request, *args, **kwargs):  
        if self.request.user.is_anonymous:  
            template = loader.get_template('base.html')
            return HttpResponse(template.render())  
        return super(AuthorEdit, self).dispatch(request, *args, **kwargs) 

class AuthorList(ListView):
    model = Author
    template_name = 'authors_list.html'

@login_required
def AuthorCreateMany(request):
    AuthorFormSet = formset_factory(AuthorForm, extra=2)
    if request.method == 'POST':
        author_formset = AuthorFormSet(request.POST, request.FILES, prefix='author')
        for author_form in author_formset:
            if author_form.is_valid() and author_form.has_changed():
                author_form.save()
        return HttpResponseRedirect(reverse_lazy('p_library:authors_list'))
    else:
        author_formset = AuthorFormSet(prefix='author')
    return render(request, 'manage_authors.html', {'author_formset': author_formset})

@login_required
def BooksAuthorsCreateMAny(request):
    AuthorFormSet = formset_factory(AuthorForm, extra=2)
    BookFormSet = formset_factory(BookForm, extra=2)
    if request.method == 'POST':
        author_formset = AuthorFormSet(request.POST, request.FILES, prefix='authors')
        book_formset = BookFormSet(request.POST, request.FILES, prefix='books')
        for author_form in author_formset:
            if author_form.is_valid() and author_form.has_changed():
                author_form.save()
        for book_form in book_formset:
            if book_form.is_valid() and book_form.has_changed():
                book_form.save()
        # return HttpResponseRedirect(reverse_lazy('/index/'))
        return redirect('/index/')
    else:
        author_formset = AuthorFormSet(prefix='authors')
        book_formset = BookFormSet(prefix='books')
    return render(
        request, 'manage_books_authors.html', {
            'author_formset': author_formset,
            'book_formset': book_formset,
        }
    )


def Friends(request):
    template = loader.get_template('friend_list.html')
    friends = Friend.objects.all().prefetch_related('books')
    return HttpResponse(template.render({'friends': friends}, request))

class FriendCreate(LoginRequiredMixin, CreateView):
    model = Friend
    form_class = FriendForm
    success_url = reverse_lazy('p_library:friend_list')
    template_name = 'friend_edit.html'
    login_url = 'account_login'

class FriendUpdate(LoginRequiredMixin, UpdateView):
    model = Friend
    form_class = FriendForm
    success_url = reverse_lazy('p_library:friend_list')
    template_name = 'friend_edit.html'
    login_url = 'account_login'

def FriendDelete(request):
    if request.method == 'POST':
        friend_id = request.POST['id']
        if not friend_id:
            return redirect('/editing/friend/')
        else:
            friend = Friend.objects.filter(id=friend_id).first()
            if not friend:
                return redirect('/editing/friend/')
            friend.delete()
        return redirect('/editing/friend/')
    else:
        return redirect('/editing/friend/')

def AuthorDelete(request):
    if request.method == 'POST':
        author_id = request.POST['id']
        if not author_id:
            return redirect('/editing/author/')
        else:
            author = Author.objects.filter(id=author_id).first()
            if not author:
                return redirect('/editing/author/')
            author.delete()
        return redirect('/editing/author/')
    else:
        return redirect('/editing/author/')

class PublisherCreate(LoginRequiredMixin, CreateView):
    model = Publisher
    form_class = PublisherForm
    success_url = reverse_lazy('publishers')
    template_name = 'publisher_edit.html'
    login_url = 'account_login'

p_library/templates/all_links.html
{% extends 'base.html' %}

{% block title %}
Список ссылок
{% endblock %}
{% block content %}
    {% load socialaccount %}
    <h2>Список ссылок</h2>
    {% if user.is_authenticated %}
        <p>Зарегистрированные пользователи могут просматривать и редактировать материал</p>
    {% else %}
        <p>Незарегистрированные пользователи могут только просматривать материал</p>
    {% endif %}
    <a href={% url 'main_page' %}>Index</a><br>
    <a href={% url 'p_library:authors_list' %}>Все авторы</a><br>
    {% if user.is_authenticated %}
        <a href={% url 'p_library:author_create' %}>Добавить автора</a><br>
        <a href={% url 'p_library:author_create_many' %}>Добавить несколько авторов</a><br>
        <a href={% url 'p_library:author_book_create_many' %}>Добавтиь несколько авторов и книг</a><br>
        <a href={% url 'publisher_create' %}>Добавить издательство</a><br>
        <a href={% url 'p_library:friend_create' %}>Добавить друга</a><br>
    {% endif %}
    <a href={% url 'publishers' %}>Издательства и их книги</a><br>
    <a href={% url 'p_library:friend_list' %}>Список друзей, задолжавших книги</a><br>
{% endblock %}

p_library/templates/author_edit.html
{% extends 'base.html' %}

{% block title %}
Добавление автора
{% endblock %}
{% block content %}
	<form method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" value="Сохранить" class="btn btn-primary">
	</form>
{% endblock %}

p_library/templates/authors_list.html
{% extends 'base.html' %}

{% block title %}
Все авторы
{% endblock %}
{% block content %}
{% load socialaccount %}
	<ul>
		{% for author in object_list %}
		    <li>{{ author.full_name }}
				{% if user.is_authenticated %}
					<form action="/editing/author/delete/" method="post" enctype="multipart/form-data">
						{% csrf_token %}
						<input type="hidden" name="id" value="{{author.id}}" />
						<input type="submit" value="Del" class="btn btn-primary"/>
					</form>
				{% endif %}
			</li>
		{% endfor %}
	</ul>
{% endblock %}

p_library/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% load static %}
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <title>{% block title %}{% endblock %}</title>
    </head>
    <body>
        <div class="container bg-light">
            <div class="row">
                <div class="col-md-8">
                    {% load socialaccount %}
                    {% if user.is_authenticated %}
                        <h3>{{ user.username }}</h3>
                        <a href={% url 'account_logout' %}>Выйти</a>                        
                    {% else %}
                        <p>Анонимные пользователи могут только просматривать материал, пожалейста, войдите.</p>
                        <a href={% url 'account_login' %}>Войти</a>
                    {% endif %}
                    <br>
                    {% block content %}
                    {% endblock %}
                    {% url 'all_links' as all %}
                    {% if not all == request.path %}
                        <a href="{{ all }}" class="nav-link active text-info">Обратно ко всем ссылкам</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </body>
</html>

p_library/templates/friend_edit.html
{% extends 'base.html' %}

{% block title %}
Добавление друга-должника
{% endblock %}
{% block content %}
	<form method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" value="Сохранить" class="btn btn-primary" style="margin: 1px;">
	</form>
	<p>Используйте ctrl, чтобы выделить несколько книг</p>
{% endblock %}

p_library/templates/friend_list.html
{% extends 'base.html' %}

{% block title %}
Должники
{% endblock %}
{% block content %}
    <h2>Список задолжавших друзей</h2>
    {% if friends %}
    {% load socialaccount %}
        {% for friend in friends %}
            <h3>{{ forloop.counter }}. {{ friend }}</h3>
                {% if user.is_authenticated %}
                    {% url 'p_library:friend_update' friend.id  as fr_edit %}
                    <a href="{{ fr_edit }}" class="btn btn-primary" style="width: 10%; margin: 1px;">Edit</a>
                    <form action="/editing/friend/delete/" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <input type="hidden" name="id" value="{{friend.id}}" />
                        <input type="submit" value="Del" class="btn btn-primary" style="width: 10%; margin: 1px;"/>
                    </form>
                {% endif %}
            <table class="table table-striped" style="width: 50%">
                {% if friend.books %}
                    {% for book in friend.books.all %}
                        <tr>
                            <td style="width: 50%">
                                {% for author in book.authors.all %}
                                    {{ author.full_name }}
                                        {% if forloop.counter != book.authors.all|length %}
                                            ,
                                        {% endif %}
                                {% endfor %}
                            </td>
                            <td style="width: 40%">
                                {{ book.title }}
                            </td>
                        </tr>
                    {% endfor %}
                {% endif %}
            </table>
        {% endfor %}
    {% endif %}
    {% url 'p_library:friend_create' as fr_create %}
    <a href="{{ fr_create }}" class="btn btn-primary" style="width: 15%; margin: 1px;">Add friend</a>
{% endblock %}

p_library/templates/index.html
{% extends 'base.html' %}

{% block title %}
Весь список книг
{% endblock %}
{% block content %}
Добро пожаловать в {{ title }}.  <br>
Тут собрано {{ books|length }} книг из моей личной коллекции.
    {% load socialaccount %}
    <table border="1">
        {% for book in books %}
            <tr>
                <td><img src="{{ book.get_image_url }}" height="100" width="100"></td>
                <td>{{ book.title }}</td>
                <td>{{ book.ISBN }}</td>
                <td>{{ book.description }}</td>
                <td>{{ book.year_release }}</td>
                <td>
                    {% for author in book.authors.all %}
                        {{ author.full_name }}
                        {% if forloop.counter != book.authors.all|length %}
                            ,
                        {% endif %}
                    {% endfor %}
                </td>
                <td>{{ book.copy_count }}</td>
                    {% if user.is_authenticated %}
                        <td>
                            <form action="/index/book_increment/" method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                <input type="hidden" name="id" value="{{book.id}}" />
                                <input type="submit" value="Увеличить кол-во" class="btn btn-primary" style="width: 100%; margin: 1px;"/>
                            </form>
                            <form action="/index/book_decrement/" method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                <input type="hidden" name="id" value="{{book.id}}" />
                                <input type="submit" value="Уменьшить кол-во" class="btn btn-primary" style="width: 100%; margin: 1px;"/>
                            </form>
                        </td>
                    {% endif %}
            </tr>
        {% endfor %}
    </table>
{% endblock %}

p_library/templates/manage_authors.html
{% extends 'base.html' %}

{% block title %}
Добавить несколько авторов
{% endblock %}
{% block content %}
	<form method="post">
		{% csrf_token %}
		{{ author_formset.management_form }}
		{% for form in author_formset %}
			{{ form.as_ul }}
			<br>
		{% endfor %}
	    <input type="submit" value="Сохранить" class="btn btn-primary"/>
	</form>
{% endblock %}

p_library/templates/manage_books_authors.html
{% extends 'base.html' %}

{% block title %}
Добавить несколько авторов и книг
{% endblock %}
{% block content %}
    <p>Можно оставить любое количество форм пустыми</p>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ author_formset.management_form }}
        {% for form in author_formset %}
            <p>Автор</p>
            <br>
            {{ form.as_ul }}
            <br>
        {% endfor %}
        {{ book_formset.management_form }}
        {% for form in book_formset %}
            <p>Книга</p>
            <br>
            {{ form.as_ul }}
            <br>
        {% endfor %}
            <input type="submit" value="Сохранить" class="btn btn-primary"/>
    </form>
{% endblock %}

p_library/templates/publisher_edit.html
{% extends 'base.html' %}

{% block title %}
Добавление издательств
{% endblock %}
{% block content %}
	<form method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" value="Сохранить" class="btn btn-primary">
	</form>
{% endblock %}

p_library/templates/publishers.html
{% extends 'base.html' %}

{% block title %}
Издательства
{% endblock %}
{% block content %}
    <h2>Список книг с издательствами</h2>
    {% if publishers %}
        {% for publisher in publishers %}
            <ul>
                <li>{{ publisher }}
                    <ul>
                        {% for book in books %}
                            {% if publisher == book.publisher.name %}
                                <li>Автор:
                                    {% for author in book.authors.all %}
                                        {{ author.full_name }}
                                            {% if forloop.counter != book.authors.all|length %}
                                                ,
                                            {% endif %}
                                    {% endfor %}
                                , Название: {{ book.title }}</li>
                            {% endif %}
                        {% endfor %}
                    </ul>
                </li>
            </ul>
        {% endfor %}
    {% endif %}
{% endblock %}